name: SuperBet
main:  me.purplefishh.dipcraft.superbet.Main
version: 1.4.4
author: PurpleFishh
api-version: 1.13
depend: [Vault]
commands:
   bet:
      description: Betting command
      usage: /bet [command]